version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    volumes:
    - .:/usr/src/app

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    networks:
      - appnet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - './.docker/postgres/:/docker-entrypoint-initdb.d/'
  redis:
    image: redis:alpine
    volumes:
      - .docker/redis:/data
    command: redis-server
    networks:
      - appnet
    ports:
      - ${REDIS_PORT}:6379
networks:
  appnet:
    driver: bridge